name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies && Build assets
        run: |
          npm install --frozen-lockfile
          npm run docs:build
          # 自定义域名
          echo 'www.celeter.tk' > docs/.vuepress/dist/CNAME

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
